version: '3'
services:
    api:
        build:
            dockerfile: Base.Dockerfile
            context: ../build/package/
        image: ${APP_NAME:-cloudbilling}:base
        security_opt:
            - seccomp:unconfined
        command: dlv debug . -l 0.0.0.0:2345 --headless=true --log=true
        volumes:
            - ../:/go/src/github.com/radisvaliullin/cloudbilling
        env_file:
            - ../build/package/dev_config.env
        environment:
            - PROFILE=DEV
        ports:
            - "2345:2345"
            - "8080:8080"
        expose:
            - "2345"
            - "8080"
        container_name: ${APP_NAME:-cloudbilling}-api-debug
        networks: 
            - default-network
        depends_on: 
            - postgres
    postgres:
        build:
            dockerfile: PG.Dockerfile
            context: ../build/package/
        environment:
            - POSTGRES_USER=cloudbilling
            - POSTGRES_PASSWORD=cloudbilling
        ports:
            - '5432:5432'
        container_name: ${APP_NAME:-cloudbilling}-postgres
        networks: 
            - default-network

networks:
  default-network: