version: '3'
services:
    api:
        build:
            dockerfile: Base.Dockerfile
            context: ../build/package/
        image: ${APP_NAME:-cloudbilling}:base
        command: sh -c "go run *.go"
        volumes:
            - ../:/go/src/github.com/radisvaliullin/cloudbilling
        env_file:
            - ../build/package/dev_config.env
        environment:
            - PROFILE=DEV
        ports:
            - "8080:8080"
        container_name: ${APP_NAME:-cloudbilling}-api
        networks: 
            - default-network
        depends_on: 
            - postgres
    postgres:
        build:
            dockerfile: PG.Dockerfile
            context: ../build/package/
        volumes:
            - cloudbilling-pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=cloudbilling
            - POSTGRES_PASSWORD=cloudbilling
        ports:
            - '5432:5432'
        container_name: ${APP_NAME:-cloudbilling}-postgres
        networks: 
            - default-network

networks:
  default-network:

volumes:
    cloudbilling-pgdata:
        external:
            name: cloudbilling-pgdata
