swagger: '2.0'
info:
  description: "REST API of xproject service that provides a fair comparison of prices for cloud services."
  version: "1.0.0"
  title: "xproject service"
  contact:
    email: "xproject_team@epam.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "http://xproject.epam.com"
basePath: "/v2"
tags:
- name: "instance"
  description: "Shows all information about instance"
schemes:
- "http"
paths:
  /instance:
    get:
      tags:
      - "instance"
      summary: "Get all instances"
      description: "Returns all avaliable instances"
      operationId: "getAllInstance"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Instances"
        404:
          description: "Instances not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - api_key: []
  /instance/{instanceID}:
    get:
      tags:
      - "instance"
      summary: "Get instance by ID"
      description: "Returns information about instance by ID"
      operationId: "getInstanceByID"
      produces:
      - "application/json"
      parameters:
      - name: "instanceID"
        in: "path"
        description: "ID of instance to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Instance"
        400:
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Instance not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - api_key: []
    delete:
      tags:
      - "instance"
      summary: "Deletes an instance from list"
      description: ""
      operationId: "deleteInstance"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "instanceID"
        in: "path"
        description: "Instance id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Instance not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - xproject_auth:
        - "write:instances"
        - "read:instances"
  /instance/{instanceID}/history:
    get:
      tags:
      - "instance"
      summary: "Get instance's history"
      description: "Returns history timeline by ID"
      operationId: "getInstanceHistoryByID"
      produces:
      - "application/json"
      parameters:
      - name: "instanceID"
        in: "path"
        description: "ID of instance to return"
        required: true
        type: "integer"
        format: "int64"
      - name: "start"
        in: "query"
        description: "Start point of history timeline (Epoch time)"
        required: false
        type: "integer"
        format: "int64"
      - name: "end"
        in: "query"
        description: "End point of history timeline (Epoch time)"
        required: false
        type: "integer"
        format: "int64"
      - name: "interval"
        in: "query"
        description: "Aggregation period [hour, day, week, month]"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/History"
        400:
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Instance not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - api_key: []
securityDefinitions:
  xproject_auth:
    type: "oauth2"
    authorizationUrl: "http://xproject.epam.com/oauth/dialog"
    flow: "implicit"
    scopes:
      write:instances: "modify instances in your account"
      read:instances: "read your instances"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Instance:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      provider:
        type: "string"
        example: "aws"
        enum:
        - "aws"
        - "gcp"
      type:
        type: "string"
        example: "ec2"
      cores:
        type: "number"
        format: "float"
      ram:
        type: "number"
        format: "float"
      disk:
        type: "number"
        format: "float"
      diskType:
        type: "string"
        example: "ssd"
        enum:
        - "ssd"
        - "hdd"
      pricePerMonth:
        type: "number"
        format: "float"
      pricePerHour:
        type: "number"
        format: "float"
      leaseType:
        type: "string"
        example: "hourly"
        enum:
        - "hourly"
        - "monthly"
        - "on demand"
      location:
        type: "string"
        example: "us-east-1"
  Instances:
    type: array
    items:
      $ref: "#/definitions/Instance"
  History:
    type: array
    items:
      type: "number"
      format: "float"
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
